lockc-project/lockc

.gitignore
Vagrantfile
contrib/crio/00-default.conf
contrib/systemd/enclave.service
contrib/vagrant/addons.sh
contrib/vagrant/base.sh
contrib/vagrant/build.sh
contrib/vagrant/control-plane-base.sh
contrib/vagrant/control-plane.sh
contrib/vagrant/kubeconfig.sh
contrib/vagrant/vagrant-fix.sh
src/bpf/enclave.bpf.c

Currently it suppports only AIO single-node installations based on Kubic
and kubeadm.
Fixes: #11

vagrant: Add the development environment

---

src/bpf/enclave.bpf.c

This PR contains two small fixes for BPF programs, which are going to unlock the follow-up work on #3
---
**bpf: Fix the hash function**
Before this change, the hash function didn't terminate on the end of
string.
---
**bpf: Check for runtime process after checking the parent**
This change changes the order of the process lookup. From now on, the
order is:
1) Check if the parent process is included in any container.
2) If no:
a) Check whether the current process is a container runtime process.
b) If yes, add a new container and register the new process.
If no, nothing to do.
If yes:
a) Add the new process as a containerized process belonging to
parent's container.

Fixes for BPF programs

---

Cargo.toml
src/lib.rs
src/settings.rs

This change allows to configure the list of runtime processes through a
configuration file (`/etc/enclave/enclave.toml`). The default list is:
- conmon
- containerd-shim

enclave: Make the list of runtime process comms configurable

---

Dockerfile

Get always the newest version instead of defining the tag by hand.
This change also switches from using git.kernel.org to downloading a
tarball from kernel.org.

docker: Fetch the newest kernel sources automatically

---

README.md
src/lib.rs

Add a widget and mentions abot the #lockc channel on the Rust Cloud
Native server.

docs: readme: Add information about Discord channel

---

Cargo.toml

Apparently dependabot can't rebase sometimes, lol
Updates the requirements on [libbpf-cargo](https://github.com/libbpf/libbpf-rs) to permit the latest version.
- [Release notes](https://github.com/libbpf/libbpf-rs/releases)
- [Commits](https://github.com/libbpf/libbpf-rs/commits)
---
updated-dependencies:
- dependency-name: libbpf-cargo
dependency-type: direct:production
...
Signed-off-by: dependabot[bot] <support@github.com>

Update libbpf-cargo requirement from 0.7 to 0.9

---

README.md

This change links to the mdbook as the main website / documentation,
while keeping the docs.rs link as the secondary one.

readme: Link to the mdbook

---

contrib/terraform/libvirt/cloud-init/control-plane.tpl
contrib/terraform/libvirt/control-plane.tf
docs/src/SUMMARY.md
docs/src/demos/README.md
docs/src/demos/mount.md
docs/src/policies/README.md
examples/kubernetes/deployments-should-fail.yaml
examples/kubernetes/deployments-should-succeed.yaml
examples/kubernetes/namespaces.yaml

This change adds a demo from asciinema about mount policies being
enforced on Kubernetes pods.

docs: Add demos with mount policies on Kubernetes

---

Dockerfile

Currently the `latest` tag of rust image on dockerhub is using Debian
bullseye instead of buster.

docker: Use llvm repo for Debian bullseye

---

README.md
docs/src/README.md
docs/src/containers-do-not-contain.md

That section explains our concerns about container security and shows
examples of potentially malicious activity which we would like to
restrict with lockc.

docs: Add "Containers do not contain" section

---

docs/src/README.md
docs/src/SUMMARY.md

docs: Fix links to the "Containers do not contain" section

---

README.md

readme: Fix typo in CDNC link

---

lockc/Cargo.toml
lockc/src/bpfstructs.rs
lockc/src/lib.rs
lockc/src/settings.rs
xtask/Cargo.toml

Rust 2021 edition comes tiwht Rust 1.56.0. Details about the new
edition:
https://blog.rust-lang.org/2021/10/21/Rust-1.56.0.html

Switch to Rust 2021

---

lockc/src/runc.rs

--process options comes with `runc exec` command. Handling this option
makes `kubectl exec` possible.
Fixes: #86

runc: Handle --process option

---

.dockerignore
.github/workflows/container-image.yml
Dockerfile

We had problems with building based on the official Rust image, based on
Debian. It's more convenient if we just stick to openSUSE and manage all
dependencies ourselves.
This PR also adds container builds for pull requests. For two reasons:
1) In case of failures on the main branch, to check whether a pull request aiming to fix them really fixes them.
2) Might be nice for testing someones' changes before merging, without necessity to check out and build their code.

docker: Use openSUSE Leap as a base image for all stages

---

.github/workflows/container-image.yml

We would like to build container images only on push to main branch.
We shouldn't care about building images from PR.

Build container images on push

---

contrib/etc/lockc/lockc.toml
contrib/helm/lockc/templates/configmap.yaml
contrib/helm/lockc/templates/daemonset.yaml
lockc/src/settings.rs

The most of the containerized workloads do not need to interact with the Kubernetes API server and
they don't need to read the token that is associated with the ServiceAccount used to create the Pod.
This path can be blocked /var/run/secrets/kubernetes.io

Restrict access to K8s secret token

---

examples/kubernetes/deployments-should-succeed.yaml

In Kubernetes v1.23 new admission controller requires securityContext
for application deployed in restricted namespaces. We need to update
lockc example deployment.
Fixes: #117
Signed-off-by: Michal Jura <mjura@suse.com>

Adopt examples to Kuberentes v1.23

---

examples/kubernetes/deployments-should-fail.yaml
examples/kubernetes/deployments-should-succeed.yaml

Original nginx images can't runAsNonRoot user we have to switch to better tuned
bitnami nginx latest 1.21.4 images. This makes examples running in restricted
namespace for Kubernetes v1.23

Switch to bitnami/nginx:1.21.4 containers

---

contrib/etc/lockc/lockc.toml
lockc/src/settings.rs

Before this change, lockc configuration was aware only of overlay2
storage driver in Docker. That was causing all containers using any
other storage driver to be prevented from running by lockc. This change
fixes that by allowing all drivers.
Fixes: #122

settings: Add all Docker stoage drivers

---

Dockerfile
lockc/src/runc.rs

runc: Remove unused fields, stop pinning to old Rust version

---

.clang-format
lockc/src/bpf/compiler.h
lockc/src/bpf/lockc.bpf.c
lockc/src/bpf/strutils.h

In our eBPF programs, we try to follow the Linux kernel coding style[0]
which is violated by default behavior of clang-format and editors using
it. This configuration fixes that.

clang-format: Honor the Linux kernel coding style

---

lockc/src/bin/lockcd.rs
lockc/src/bpf/lockc.bpf.c
lockc/src/bpf/maps.h
lockc/src/lib.rs

Before this change, each restart of lockc resulted in loss of data in
BPF maps. After this change, data is persistent as long as the host
system is not rebooted. All maps are pinned to BPPFS and lockc attempts
to reuse them if they're present.
Fixes: #130

Try to reuse pinned BPF maps

---

lockc/src/bpf/lockc.bpf.c
lockc/src/bpf/maps.h
lockc/src/lib.rs

That map is not needed anymore. We detect the runtime processes in the
userspace with fanotify, there is no need for any eBPF logic for that.

Remove `runtimes` map

---

lockc/src/settings.rs

Currently lockcd ignores `/etc/lockc/lockc.toml` configuration file,
because we are setting option in incorrect way. We have to set them as defaults.
Fixes #152

Set proper default options for lockcd

---

lockc/src/bin/lockcd.rs
lockc/src/lib.rs

In pull request #142 we made a mistake of converting lockc into full
binary crate, therefore renaming lockcd to lockc and removing a
possibility of creating multiple binaries (if there will be a need -
i.e. for some CLI tool).
This change fixes that by creating a bin/ directory with binaries again.

Ensure that the binary is named lockcd

---

lockc/src/bpf/lockc.bpf.c
lockc/src/load.rs

We have decided to implement new LSH hook which disable root user in container.
Fix #85
Expected output with this feature enabled:
```
opensuse@mjura-dev:~> sudo -i
sudo: PERM_ROOT: setresuid(0, -1, -1): Operation not permitted
sudo: error initializing audit plugin sudoers_audit
opensuse@mjura-dev:~> su - root
Password: 
su: cannot set user id: Operation not permitted
```

Add new LSM_HOOK to restrict root user

---

lockc/build.rs
lockc/src/bin/lockcd.rs
lockc/src/runc.rs
lockc/src/sysutils.rs
xtask/src/bintar.rs
xtask/src/install.rs

Use references, stop overusing clone()

---

lockc/src/runc.rs

Flatcar Linux uses torcx[0] to install addons on immutable Linux
distributions and one of them is runc. To support Flatcar, we need to
monitor runc path comming from torcx as well.
[0] https://github.com/flatcar-linux/torcx
Fixes: rancher-sandbox/lockc-helm-charts#9

runc: Add path used by torcx and Flatcar Linux

---

contrib/terraform/libvirt/deploy-kubernetes.sh
contrib/terraform/openstack/deploy-kubernetes.sh

Spinning up VMs was sometimes failing on scp (of kubeconfig) due to
strict key check.

terraform: Disable strict key checking on scp

---

Dockerfile
docs/src/developers/terraform/libvirt.md
lockc/Cargo.toml
lockc/src/bin/lockcd.rs

Change to Aya as the eBPF loader in the userpace (#142) broke few things in the Kubernetes integration. This PR fixes them. Best to be reviewed per commit.

Fix lockc on Kubernetes

---

lockc/src/bin/lockcd.rs

According to docs of tokio::sync::oneshot::Sender.send, that method
"attempts to send a value on this channel, returning it back if it could
not be sent."
Err case of send() is just simply returning the sent value back. Quite
confusing, I was expecting some real error there. But well, according to
the example snippet:
https://docs.rs/tokio/1.16.1/tokio/sync/oneshot/struct.Sender.html#examples-1
we are just logging a custom error there.

tokio: Fix the way of using oneshot::Sender

---

Dockerfile

Before this change, building container images was long and annoying,
cargo was downloading and building dependencies from scratch every time.
This commit fixes that by caching cargo artifacts.

docker: Cache cargo builds

---

lockc/src/bin/lockcd.rs

To make developer's life easier and don't bother them with using
--log-lever every time. When building with debug profile, we usually
expect debug logs.

lockcd: Set default log level to debug when building with debug profile

---

Dockerfile

rust-gdb and rust-lldb binaries are shipped in rust package. And both of
them need also python3-lldb to work.

docker: Add missing packages for rust-{gdb,lldb} debuggers

---

lockc/src/bin/lockcd.rs
lockc/src/bpf/maps.h
lockc/src/load.rs
lockc/src/maps.rs

Aya relies on the `pinning` field in BPF map definitions. libbpf doesn't
provide that field, so instead of using their bpf_map_def struct, here
we define our bpf_elf_map struct which has it.
Our structure is similar to those available in Cilium[0] and some
selftests in the kernel tree[1].
[0] https://github.com/cilium/cilium/blob/v1.11.1/bpf/include/bpf/loader.h#L19-L29
[1] https://elixir.bootlin.com/linux/v5.16.8/source/samples/bpf/tc_l2_redirect_kern.c#L23
Fixes: #169

bpf: Fix map pinning

---

lockc/Cargo.toml
lockc/src/bin/lockcd.rs
lockc/src/maps.rs
lockc/src/settings.rs

That update deprecated the way we used `config` crate. We used to wrap
the whole config into out struct and convert config::Config into it.
After this change, we rather use config::Config directly. We also read
the file in asynchronous way by using AsyncSource trait.

Update config to 0.12

---

contrib/terraform/libvirt/provision-k8s-containerd-cp.sh
contrib/terraform/libvirt/provision-k8s-containerd.sh
contrib/terraform/openstack/provision-k8s-containerd-cp.sh
contrib/terraform/openstack/provision-k8s-containerd.sh

* containerd wasn't properly downloaded in lbivirt
* add -sSL option to curl everywhere
* download crictl, which is required by kubeadm now

terraform: Fix VM provisioning

---

docs/src/developers/terraform/libvirt.md

We deploy lockc in its own namespace, not kube-system.

docs: Fix the namespace in kubectl command

---

lockc/src/bin/lockcd.rs

It's /sys/fs/bpf/lockc by default, which of course doesn't exists on
fresh systems.

lockcd: Ensure that the base path is created

---

lockc-common/src/lib.rs
lockc-ebpf/Cargo.toml
lockc-ebpf/src/main.rs
lockc-ebpf/src/maps.rs
lockc/src/load.rs

This program is trggered by opening a file and denies access to
directories which might leak information about host (/sys/fs, /proc/acpi
etc.).
Fixes: #139

Add file_open LSM program

---

lockc-ebpf/src/main.rs

This change allows bind mounts related to Kubenetes and k3s.

ebpf(sb_mount): Add Kubernetes directories

---

lockc/Cargo.toml
lockc/src/runc.rs

Looking for runc binary shipped with k3s is a bit trickier, because
it comes in the /var/lib/rancher/k3s/data/[ID] directory where ID is
random. We need to walk through /var/lib/rancher/k3s.

runc: Add k3s runc binaries to fanotify

---

examples/kubernetes/nginx-should-fail.yaml
examples/kubernetes/nginx-should-succeed.yaml

One of them (the "standard" one ( ͡° ͜ʖ ͡°) ) is running as root, therefore
denied by lockc.
The other one, provided by bitnami, deploys successfully.

examples: Add example nginx deployments

---

lockc-ebpf/src/main.rs

bpf(file_open): Hide whole /sys except cgroup, devices and kernel/mm

---

Vagrantfile

Install bpftool to be able to use aya-tool inside. Also, perform a dist-upgrade to always get the newest kernel.

vagrant: Install bpftool, do dist-upgrade

---

Vagrantfile

Make it disabled by default. It can be enabled with the `LOCKC_VAGRANT_K8S` environment variable.

vagrant: Make k8s deployment optional

---

Cargo.lock
lockc/Cargo.toml
lockc/src/main.rs

The way we manually parsed the log level from string is not supported anymore and it's a good opportunity to do it cleaner with enums.

Update clap, use `ValueEnum`
